"""
STrackSLSTM — STrack extended with a per-track token history buffer for sLSTM.

Drop-in replacement for the original STrack when using BYTETrackerSLSTM.
The original ByteTrack code is untouched; this class only adds fields
needed by the sLSTM predictor.
"""

from collections import deque

import numpy as np

from yolox.tracker.basetrack import BaseTrack, TrackState
from yolox.tracker.kalman_filter import KalmanFilter


class STrackSLSTM(BaseTrack):
    """
    Fields added over the original STrack
    ──────────────────────────────────────
    token_buffer     : per-track token history (deque of ints, 4 tokens per frame)
    pred_bbox_cxcywh : sLSTM-corrected predicted bbox [cx, cy, w, h] in pixels
    _pred_tokens     : scratch space: last 4 tokens generated by sLSTM
    velocity         : [vx, vy] from consecutive detections
    missing_count    : consecutive frames without a matched detection
    is_missing       : 1 if current frame has no match, else 0
    last_confidence  : detection score of the last matched detection
    """

    shared_kalman = KalmanFilter()

    def __init__(
        self,
        tlwh: np.ndarray,
        score: float,
        context_length: int = 256,
    ):
        # ── Kalman state ─────────────────────────────────────────────────
        self._tlwh = np.asarray(tlwh, dtype=np.float64)
        self.kalman_filter: KalmanFilter | None = None
        self.mean: np.ndarray | None = None
        self.covariance: np.ndarray | None = None
        self.is_activated: bool = False

        self.score = score
        self.tracklet_len = 0

        # ── sLSTM token buffer ───────────────────────────────────────────
        self.context_length = context_length
        self.token_buffer: deque = deque(maxlen=context_length)

        # ── Motion history ───────────────────────────────────────────────
        self.last_bbox_cxcywh = self._tlwh_to_cxcywh(tlwh)
        self.velocity = np.zeros(2, dtype=np.float32)

        # ── Missing-aware state ──────────────────────────────────────────
        self.missing_count: int = 0
        self.is_missing: int = 0
        self.last_confidence: float = float(score)

        # ── Scratch space filled by BYTETrackerSLSTM before matching ─────
        self.pred_bbox_cxcywh: np.ndarray = self.last_bbox_cxcywh.copy()
        self._pred_tokens: np.ndarray = np.zeros(4, dtype=np.int64)

    # ── Kalman interface (mirrors original STrack) ───────────────────────────

    def predict(self):
        mean_state = self.mean.copy()
        if self.state != TrackState.Tracked:
            mean_state[7] = 0
        self.mean, self.covariance = self.kalman_filter.predict(
            mean_state, self.covariance
        )

    @staticmethod
    def multi_predict(stracks: list["STrackSLSTM"]):
        if not stracks:
            return
        multi_mean = np.array([s.mean.copy() for s in stracks])
        multi_cov = np.array([s.covariance for s in stracks])
        for i, s in enumerate(stracks):
            if s.state != TrackState.Tracked:
                multi_mean[i][7] = 0
        multi_mean, multi_cov = STrackSLSTM.shared_kalman.multi_predict(
            multi_mean, multi_cov
        )
        for i, (m, c) in enumerate(zip(multi_mean, multi_cov)):
            stracks[i].mean = m
            stracks[i].covariance = c

    def activate(self, kalman_filter: KalmanFilter, frame_id: int):
        self.kalman_filter = kalman_filter
        self.track_id = self.next_id()
        self.mean, self.covariance = self.kalman_filter.initiate(
            self.tlwh_to_xyah(self._tlwh)
        )
        self.tracklet_len = 0
        self.state = TrackState.Tracked
        self.is_activated = frame_id == 1
        self.frame_id = frame_id
        self.start_frame = frame_id
        self.pred_bbox_cxcywh = self._tlwh_to_cxcywh(self._tlwh)

    def re_activate(self, new_track: "STrackSLSTM", frame_id: int, new_id: bool = False):
        self.mean, self.covariance = self.kalman_filter.update(
            self.mean, self.covariance, self.tlwh_to_xyah(new_track.tlwh)
        )
        self.tracklet_len = 0
        self.state = TrackState.Tracked
        self.is_activated = True
        self.frame_id = frame_id
        if new_id:
            self.track_id = self.next_id()
        self.score = new_track.score
        self._reset_missing()

    def update(self, new_track: "STrackSLSTM", frame_id: int):
        self.frame_id = frame_id
        self.tracklet_len += 1
        self.mean, self.covariance = self.kalman_filter.update(
            self.mean, self.covariance, self.tlwh_to_xyah(new_track.tlwh)
        )
        self.state = TrackState.Tracked
        self.is_activated = True
        self.score = new_track.score
        self._reset_missing()

    # ── Token buffer helpers ─────────────────────────────────────────────────

    def append_tokens(self, tokens: np.ndarray):
        """Append 4 tokens (one frame) to the token buffer."""
        for t in tokens:
            self.token_buffer.append(int(t))

    def apply_slstm_matched(self, det_bbox_cxcywh: np.ndarray, det_score: float):
        """Commit state after a real detection match."""
        self.velocity = (det_bbox_cxcywh[:2] - self.last_bbox_cxcywh[:2]).astype(np.float32)
        self.last_bbox_cxcywh = det_bbox_cxcywh.astype(np.float32)
        self.last_confidence = float(det_score)
        self._reset_missing()

    def apply_slstm_missing(self):
        """Commit state when no detection matched this frame."""
        self.last_bbox_cxcywh = self.pred_bbox_cxcywh.astype(np.float32)
        self.last_confidence = 0.0
        self.missing_count += 1
        self.is_missing = 1
        # Append sLSTM-predicted tokens so future predictions stay coherent
        self.append_tokens(self._pred_tokens)

    def _reset_missing(self):
        self.missing_count = 0
        self.is_missing = 0

    # ── Bbox helpers ─────────────────────────────────────────────────────────

    def to_xyah(self) -> np.ndarray:
        return self.tlwh_to_xyah(self.tlwh)

    def get_kf_bbox_cxcywh(self) -> np.ndarray:
        """KF-predicted position in [cx, cy, w, h] pixel format."""
        if self.mean is None:
            return self._tlwh_to_cxcywh(self._tlwh)
        cx, cy, a, h = self.mean[:4]
        return np.array([cx, cy, a * h, h], dtype=np.float32)

    @property
    def pred_tlwh(self) -> np.ndarray:
        """sLSTM-corrected predicted bbox in [x1, y1, w, h] format."""
        cx, cy, w, h = self.pred_bbox_cxcywh
        return np.array([cx - w / 2, cy - h / 2, w, h], dtype=np.float64)

    @property
    def pred_tlbr(self) -> np.ndarray:
        """sLSTM-corrected predicted bbox in [x1, y1, x2, y2] format."""
        t = self.pred_tlwh
        return np.array([t[0], t[1], t[0] + t[2], t[1] + t[3]], dtype=np.float64)

    @property
    def tlwh(self) -> np.ndarray:
        if self.mean is None:
            return self._tlwh.copy()
        ret = self.mean[:4].copy()
        ret[2] *= ret[3]
        ret[:2] -= ret[2:] / 2
        return ret

    @property
    def tlbr(self) -> np.ndarray:
        ret = self.tlwh.copy()
        ret[2:] += ret[:2]
        return ret

    @staticmethod
    def _tlwh_to_cxcywh(tlwh: np.ndarray) -> np.ndarray:
        t = np.asarray(tlwh, dtype=np.float32)
        return np.array([t[0] + t[2] / 2, t[1] + t[3] / 2, t[2], t[3]], dtype=np.float32)

    @staticmethod
    def tlwh_to_xyah(tlwh: np.ndarray) -> np.ndarray:
        ret = np.asarray(tlwh, dtype=np.float64).copy()
        ret[:2] += ret[2:] / 2
        ret[2] /= ret[3]
        return ret

    @staticmethod
    def tlbr_to_tlwh(tlbr: np.ndarray) -> np.ndarray:
        ret = np.asarray(tlbr).copy()
        ret[2:] -= ret[:2]
        return ret

    @staticmethod
    def tlwh_to_tlbr(tlwh: np.ndarray) -> np.ndarray:
        ret = np.asarray(tlwh).copy()
        ret[2:] += ret[:2]
        return ret

    def __repr__(self):
        return f"OT_{self.track_id}_({self.start_frame}-{self.end_frame})"
